xcodeproj 'OCDKit Tests'
workspace '../OCDKit'
inhibit_all_warnings!

def import_pods
  pod 'OCMock', '~> 2.2.4'
  pod 'OCDKit', :path => '../'
end

target :ios do
  platform :ios, '7.1'
  link_with 'iOS Tests'
  import_pods
end

# target :osx do
#   platform :osx, '10.9'
#   link_with 'OS X Tests'
#   import_pods
# end
