xcodeproj 'OCDKitTest'
workspace '../OCDKit'
inhibit_all_warnings!

def import_pods
  pod 'OHHTTPStubs', '~> 3.1.0'
  pod 'Expecta', '~> 0.3.0'
  pod 'OCDKit', :path => '../'
end

target :ios do
  platform :ios, '7.1'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_pods
end
